// <auto-generated />
using System;
using ClassTracker.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassTracker.Migrations
{
    [DbContext(typeof(ClassTrackerContext))]
    [Migration("20220410050617_Teacher seed data")]
    partial class Teacherseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassTracker.Entities.TafeClass", b =>
                {
                    b.Property<int>("TafeClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TafeClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TafeClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TafeClasses");
                });

            modelBuilder.Entity("ClassTracker.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            TeacherEmail = "mhour25@eq.edu.au",
                            TeacherName = "Melissa",
                            TeacherPhone = "0410541265"
                        },
                        new
                        {
                            TeacherId = 2,
                            TeacherEmail = "ekala1@eq.edu.au",
                            TeacherName = "Erick",
                            TeacherPhone = "0415752145"
                        });
                });

            modelBuilder.Entity("ClassTracker.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TafeClassId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.HasIndex("TafeClassId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ClassTracker.Entities.TafeClass", b =>
                {
                    b.HasOne("ClassTracker.Entities.Teacher", "Teacher")
                        .WithMany("TafeClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ClassTracker.Entities.Unit", b =>
                {
                    b.HasOne("ClassTracker.Entities.TafeClass", "TafeClass")
                        .WithMany("Units")
                        .HasForeignKey("TafeClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TafeClass");
                });

            modelBuilder.Entity("ClassTracker.Entities.TafeClass", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("ClassTracker.Entities.Teacher", b =>
                {
                    b.Navigation("TafeClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
